"use client";
import React from "react";
import { Zap, Sparkles, Briefcase, Camera } from "lucide-react";

export const TAFANU_CATEGORIES: Record<string, string[]> = {
  Alimentação: [
    "Açaí & Sorvetes",
    "Adegas",
    "Cafeteria & Brunch",
    "Cervejarias & Bares",
    "Churrasco/Espetinhos",
    "Comida Saudável",
    "Docerias & Bolos",
    "Hamburguerias",
    "Marmitas & Quentinhas",
    "Pizzarias",
    "Restaurantes",
    "Sushi & Comida Japonesa",
    "Outros",
  ].sort(),
  Automotivo: [
    "Ar Condicionado Automotivo",
    "Auto Elétrica",
    "Auto Peças",
    "Borracharias",
    "Lava Jato & Estética",
    "Martelinho de Ouro",
    "Oficinas Mecânicas",
    "Pneus & Alinhamento",
    "Som & Acessórios",
    "Venda de Veículos",
    "Outros",
  ].sort(),
  "Beleza e Estética": [
    "Barbearias",
    "Bronzeamento",
    "Cílios & Sobrancelhas",
    "Clínicas de Estética",
    "Depilação a Laser",
    "Maquiagem Profissional",
    "Manicure",
    "Massagem & Spa",
    "Salões de Beleza",
    "Outros",
  ].sort(),
  "Comércio Local": [
    "Açougues",
    "Calçados",
    "Eletrônicos & Celulares",
    "Floriculturas",
    "Hortifruti / Sacolão",
    "Padarias",
    "Papelarias",
    "Presentes & Variedades",
    "Roupas & Acessórios",
    "Supermercados",
    "Suplementos",
    "Tabacaria",
    "Outros",
  ].sort(),
  Pets: [
    "Adestramento",
    "Banho e Tosa",
    "Clínicas Veterinárias",
    "Farmácia Veterinária",
    "Hospedagem Pet",
    "Passeadores (Dog Walker)",
    "Pet Shops / Rações",
    "Outros",
  ].sort(),
  Profissionais: [
    "Advogados",
    "Arquitetos & Engenheiros",
    "Consultoria de Negócios",
    "Contadores",
    "Fotógrafos & Filmagem",
    "Imobiliárias",
    "Marketing & Design",
    "Organizadores de Eventos",
    "Professores Particulares",
    "Seguros",
    "Outros",
  ].sort(),
  "Saúde e Bem-Estar": [
    "Academias",
    "Clínicas Médicas",
    "Dentistas",
    "Farmácias",
    "Fisioterapia",
    "Fonoaudiologia",
    "Nutricionistas",
    "Óticas",
    "Psicologia & Terapia",
    "Yoga & Pilates",
    "Outros",
  ].sort(),
  "Serviços Casa": [
    "Ar Condicionado",
    "Dedetização",
    "Diaristas & Faxina",
    "Eletricistas",
    "Encanadores",
    "Jardinagem",
    "Limpeza de Estofados",
    "Marcenaria",
    "Marido de Aluguel",
    "Pintores",
    "Redes de Proteção",
    "Vidraçaria",
    "Outros",
  ].sort(),
};

export const layoutInfo: any = {
  urban: {
    label: "Urban",
    icon: React.createElement(Zap, { size: 14 }),
    field: "urban_tag",
    placeholder: "@seu.estilo",
  },
  editorial: {
    label: "Luxe",
    icon: React.createElement(Sparkles, { size: 14 }),
    field: "luxe_quote",
    placeholder: "Frase elegante...",
  },
  businessList: {
    label: "Comercial",
    icon: React.createElement(Briefcase, { size: 14 }),
    field: "comercial_badge",
    placeholder: "Slogan Comercial",
  },
  showroom: {
    label: "Showroom",
    icon: React.createElement(Camera, { size: 14 }),
    field: "showroom_collection",
    placeholder: "Coleção 2026",
  },
};

export const contactPlaceholders: Record<string, string> = {
  instagram: "@seu.perfil",
  tiktok: "@seu.perfil",
  facebook: "facebook.com/suapagina",
  website: "www.seusite.com.br",
};
